
/* Drop Triggers */

DROP TRIGGER TRI_GOODS_TBL_GOODS_NUM;
DROP TRIGGER TRI_MOVIE_TBL_ MOVIE_NUM;




/* Drop Tables */

DROP TABLE ATTACH_EVENT_TBL CASCADE CONSTRAINTS;
DROP TABLE ATTACH_GOODS_TBL CASCADE CONSTRAINTS;
DROP TABLE ATTACH_INFO_TBL CASCADE CONSTRAINTS;
DROP TABLE ATTACH_MOVIE_TBL CASCADE CONSTRAINTS;
DROP TABLE AUTH_TBL CASCADE CONSTRAINTS;
DROP TABLE CSC_TBL CASCADE CONSTRAINTS;
DROP TABLE EVENT_TBL CASCADE CONSTRAINTS;
DROP TABLE GOODS_TBL CASCADE CONSTRAINTS;
DROP TABLE SEAT_TBL CASCADE CONSTRAINTS;
DROP TABLE RESERVE_TBL CASCADE CONSTRAINTS;
DROP TABLE GUEST_TBL CASCADE CONSTRAINTS;
DROP TABLE INFO_TBL CASCADE CONSTRAINTS;
DROP TABLE REPLY_TBL CASCADE CONSTRAINTS;
DROP TABLE MOVIE_TBL CASCADE CONSTRAINTS;
DROP TABLE USER_TBL CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE SEQ_GOODS_TBL_GOODS_NUM;




/* Create Sequences */

CREATE SEQUENCE SEQ_GOODS_TBL_GOODS_NUM INCREMENT BY 1 START WITH 1;



/* Create Tables */

CREATE TABLE ATTACH_EVENT_TBL
(
	EVENT_UUID varchar2(80) NOT NULL,
	EVENT_UPLOADPATH varchar2(100) NOT NULL,
	EVENT_FILENAME varchar2(100) NOT NULL,
	EVENT_BNO number NOT NULL,
	PRIMARY KEY (EVENT_UUID)
);


CREATE TABLE ATTACH_GOODS_TBL
(
	GOODS_UUID varchar2(100) NOT NULL,
	GOODS_UPLOADPATH varchar2(100) NOT NULL,
	GOODS_FILENAME varchar2(100) NOT NULL,
	GOODS_NUM number NOT NULL,
	PRIMARY KEY (GOODS_UUID)
);


CREATE TABLE ATTACH_INFO_TBL
(
	INFO_UUID varchar2(100) NOT NULL,
	INFO_UPLOADPATH varchar2(100) NOT NULL,
	INFO_FILENAME varchar2(100) NOT NULL,
	INFO_BNO number NOT NULL,
	PRIMARY KEY (INFO_UUID)
);


CREATE TABLE ATTACH_MOVIE_TBL
(
	MOVIE_UUID varchar2(100) NOT NULL,
	MOVIE_UPLOADPATH varchar2(60) NOT NULL,
	MOVIE_FILENAME varchar2(60) NOT NULL,
	movieCD number NOT NULL,
	PRIMARY KEY (MOVIE_UUID)
);


CREATE TABLE AUTH_TBL
(
	AUTHORIY varchar2(50),
	USER_ID varchar2(50) NOT NULL UNIQUE
);


CREATE TABLE CSC_TBL
(
	CSC_BNO number NOT NULL,
	CSC_TITLE varchar2(100) NOT NULL,
	CSC_CONTENT varchar2(1000) NOT NULL,
	CSC_REGDATE date DEFAULT SYSDATE,
	CSC_RFI varchar2(1000) not null,
	CSC_ANSWER varchar2(1000),
	USER_ID varchar2(50) NOT NULL UNIQUE,
	PRIMARY KEY (CSC_BNO)
);


CREATE TABLE EVENT_TBL
(
	EVENT_BNO number NOT NULL,
	EVENT_TITLE varchar2(100) NOT NULL,
	EVENT_CONTENT varchar2(1000) NOT NULL,
	EVENT_REGDATE date DEFAULT SYSDATE,
	EVENT_UPDATEDATE date DEFAULT SYSDATE,
	EVENT_CNT number,
	PRIMARY KEY (EVENT_BNO)
);


CREATE TABLE GOODS_TBL
(
	GOODS_NAME varchar2(80) NOT NULL,
	GOODS_PRICE number,
	GOODS_CONTENT varchar2(1000),
	GOODS_NUM number NOT NULL,
	PRIMARY KEY (GOODS_NUM)
);


CREATE TABLE GUEST_TBL
(
	GUEST_NUM number NOT NULL,
	GUEST_NAME varchar2(50) NOT NULL,
	GUEST_BIRTH varchar2(60) NOT NULL,
	GUEST_PASSWORD number NOT NULL,
	GUEST_EMAIL varchar2(50) NOT NULL UNIQUE,
	PRIMARY KEY (GUEST_NUM)
);


CREATE TABLE INFO_TBL
(
	INFO_BNO number NOT NULL,
	INFO_TITLE varchar2(80) NOT NULL,
	INFO_CONTENT varchar2(1500) NOT NULL,
	INFO_REGDATE date DEFAULT SYSDATE NOT NULL,
	INFO_UPDATEDATE date DEFAULT SYSDATE,
	INFO_CNT number,
	PRIMARY KEY (INFO_BNO)
);


CREATE TABLE MOVIE_TBL
(
	movieCD number NOT NULL,
	movieNM varchar2(60) NOT NULL,
	peopleNm varchar2(60),
	showTm varchar2(60),
	MOVIE_CONTENT varchar2(1200),
	genreNm varchar2(40),
	watchGradeNm char(10),
	nationNm varchar2(60),
	companys varchar2(60),
	openDt varchar2(60),
	PRIMARY KEY (movieCD)
);
select * from movie_tbl;

insert into MOVIE_TBL values(20210028,'스파이더맨: 노 웨이 홈','톰 홀랜드,베네딕트 컴버배치','148',
'이이이','액션','12','미국','Sony Pictures','2021-12-15');

CREATE TABLE REPLY_TBL
(
	replyCd number NOT NULL,
	replyer varchar2(60) NOT NULL,
	replyDate date DEFAULT SYSDATE NOT NULL,
	replyContent varchar2(300) NOT NULL,
	replygrade number,
	movieCD number NOT NULL,
	PRIMARY KEY (replyCd)
);


CREATE TABLE RESERVE_TBL
(
	scheduleNum number NOT NULL,
	movieDay varchar2(60),
	movieTime varchar2(60),
	movieRoom varchar2(60),
	movieSeat varchar2(60),
	movieCD number NOT NULL,
	USER_ID varchar2(50) NOT NULL UNIQUE,
	MoviePrice number,
	movieNm varchar2(60),
	GUEST_NUM number NOT NULL UNIQUE,
	PRIMARY KEY (scheduleNum)
);


CREATE TABLE SEAT_TBL
(
	SEAT_NM varchar2(40) NOT NULL,
	SEAT_NO number NOT NULL,
	SEAT_ENABLE char(10) DEFAULT '1' NOT NULL,
	scheduleNum number NOT NULL UNIQUE,
	movieTime varchar2(60),
	movieRoom varchar2(60),
	movieDay varchar2(60),
	PRIMARY KEY (SEAT_NO)
);


CREATE TABLE USER_TBL
(
	USER_ID varchar2(50) NOT NULL,
	USER_NAME varchar2(50) NOT NULL,
	USER_PASSWORD varchar2(50) NOT NULL,
	USER_BIRTH date NOT NULL,
	USER_EMAIL varchar2(60) NOT NULL UNIQUE,
	USER_TEL varchar2(60) NOT NULL,
	USER_REGDATE date DEFAULT sysdate NOT NULL,
	USER_ENABLE char(10) DEFAULT '1',
	PRIMARY KEY (USER_ID)
);



/* Create Foreign Keys */

ALTER TABLE ATTACH_EVENT_TBL
	ADD FOREIGN KEY (EVENT_BNO)
	REFERENCES EVENT_TBL (EVENT_BNO)
;


ALTER TABLE ATTACH_GOODS_TBL
	ADD FOREIGN KEY (GOODS_NUM)
	REFERENCES GOODS_TBL (GOODS_NUM)
;


ALTER TABLE RESERVE_TBL
	ADD FOREIGN KEY (GUEST_NUM)
	REFERENCES GUEST_TBL (GUEST_NUM)
;


ALTER TABLE ATTACH_INFO_TBL
	ADD FOREIGN KEY (INFO_BNO)
	REFERENCES INFO_TBL (INFO_BNO)
;


ALTER TABLE ATTACH_MOVIE_TBL
	ADD FOREIGN KEY (movieCD)
	REFERENCES MOVIE_TBL (movieCD)
;


ALTER TABLE REPLY_TBL
	ADD FOREIGN KEY (movieCD)
	REFERENCES MOVIE_TBL (movieCD)
;


ALTER TABLE RESERVE_TBL
	ADD FOREIGN KEY (movieCD)
	REFERENCES MOVIE_TBL (movieCD)
;


ALTER TABLE SEAT_TBL
	ADD FOREIGN KEY (scheduleNum)
	REFERENCES RESERVE_TBL (scheduleNum)
;


ALTER TABLE AUTH_TBL
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USER_TBL (USER_ID)
;


ALTER TABLE CSC_TBL
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USER_TBL (USER_ID)
;


ALTER TABLE RESERVE_TBL
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USER_TBL (USER_ID)
;



----------------------------------------밑은 사용하지마시오.. 안쓰는 코드..----------------------------



/* Create Triggers */

CREATE OR REPLACE TRIGGER TRI_GOODS_TBL_GOODS_NUM BEFORE INSERT ON GOODS_TBL
FOR EACH ROW
BEGIN
	SELECT SEQ_GOODS_TBL_GOODS_NUM.nextval
	INTO :new.GOODS_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_MOVIE_TBL_ MOVIE_NUM BEFORE INSERT ON MOVIE_TBL
FOR EACH ROW
BEGIN
	SELECT SEQ_MOVIE_TBL_ MOVIE_NUM.nextval
	INTO :new. MOVIE_NUM
	FROM dual;
END;

/

insert into user_tbl
values('id1','name1','12345','1997/10/14','id1naver.com','010-1234-5678',sysdate,'1');

insert into user_tbl
values('id2','name2','12345','1997/10/14','id2@naver.com','010-1234-5678',sysdate,'1');

select * from user_tbl;	
select * from csc_TBL;	
		select Csc_Bno,Csc_Title,Csc_Content,Csc_Regdate,Csc_Rfi,Csc_Answer,user_id
 from csc_tbl;
---
insert into csc_TBL (csc_bno,csc_title,csc_content,csc_regdate,csc_RFI,csc_answer,user_id)
values(1,'고객센터1','고객센터내용1',sysdate,'기타','처리내용1','id1');


select Csc_Bno,Csc_Title,Csc_Regdate,Csc_Rfi,user_id
 from csc_tbl

ALTER USER c##team DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

​
